#!/bin/bash
[[ -z "$*" ]] && { echo "Usage: png-to-animated-webp PNG_FILE_1 PNG_FILE_2 ..."; exit; }
frames=( )
for f in $@ ; do
    frames+=( -frame "$f" +250+0+0+0-b )
done
webpmux "${frames[@]}" -o animation.webp
